#!/usr/bin/env node
/**
 * Quickstart helper: prints the long-lived keypairs, the control token and
 * the firewall review token as .env lines. It never touches .env — copy the
 * output in yourself, so the private halves only ever live in the
 * gitignored file you chose.
 *
 *   pnpm build && node scripts/gen-keys.mjs >> .env
 *
 * The PRINCIPAL pair is DEMO CONVENIENCE ONLY: in the real design the
 * principal signs mandates elsewhere and no agent host holds that key
 * (THREAT_MODEL.md non-goals).
 */
import { randomBytes } from 'node:crypto';

const { generateKeyPair } = await import(
  new URL('../packages/protocol/dist/index.js', import.meta.url).href
);

const pairs = ['PRINCIPAL', 'FIREWALL', 'SETTLEMENT'].map((name) => [name, generateKeyPair()]);
const lines = ['', '# --- generated by scripts/gen-keys.mjs (keep in .env only) ---'];
for (const [name, kp] of pairs) {
  lines.push(`${name}_PRIVATE_KEY=${kp.privateKey}`);
  lines.push(`${name}_PUBLIC_KEY=${kp.publicKey}`);
}
lines.push(`CONTROL_TOKEN=${randomBytes(24).toString('hex')}`);
lines.push(`FIREWALL_REVIEW_TOKEN=${randomBytes(24).toString('hex')}`);
console.log(lines.join('\n'));
